from enum import Enum

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

SQUARE_FIELD_WIDTH = 50
SQUARE_FIELD_HEIGHT = 50

HEXAGON_FIELD_WIDTH = 152
HEXAGON_FIELD_SIDE_WIDTH = 48
HEXAGON_FIELD_CENTER_WIDTH = 56
HEXAGON_FIELD_WIDTH_SPACING = HEXAGON_FIELD_WIDTH - HEXAGON_FIELD_SIDE_WIDTH

SPRITE_IN_HEXAGON_WIDTH = 40
SPRITE_IN_HEXAGON_HEIGHT = 40

HEXAGON_FIELD_HEIGHT = 104


class Panels(Enum):
    AreaMap = 0
    TextAdventureBox = 1
    WorldMap = 2
    MainMenuBar = 3
